In [1]:
# Import modules
import geopandas as gpd
import numpy as np
import pandas as pd
import os
from os.path import join
import glob

In [2]:
# Set your working directory
os.chdir("../..")
working_dir = os.getcwd()

In [3]:
print(working_dir)

/home/user/These/cordex_htws_cc3d

In [4]:
# Load data
shapefile_path = join(working_dir,"Data/interactive-atlas/IPCC-WGI-reference-regions-v4_shapefile/IPCC_WG1_reference_regions_v4.gpkg") # downloaded from https://github.com/IPCC-WG1/Atlas/blob/main/reference-regions/IPCC-WGI-reference-regions-v4_shapefile.zip and added regions area in QGIS
datadir = join(working_dir,"Data/interactive-atlas/dataset-aggregated-regionally") # downloaded from https://github.com/IPCC-WG1/Atlas/tree/main/datasets-aggregated-regionally/data/CMIP6/CMIP6_tas_landsea
csv_filelist = glob.glob(join(datadir,'*historical*.csv')) # select csv files of historical runs

In [5]:
# Compute area of the 4 european zone and their fraction of sum of the 4 areas
db_ref_regions = gpd.read_file(shapefile_path)
eurocordex_regions = ['NEU','WCE','EEU','MED'] # the 4 regions overlapping at least 80% with the EUROCORDEX region, according to IPPC : https://github.com/IPCC-WG1/Atlas/blob/main/datasets-aggregated-regionally/README.md
db_europe = db_ref_regions[db_ref_regions["Acronym"].isin(eurocordex_regions)]
europe_area = db_europe["area"].sum()
weight_dict = {}
for region in eurocordex_regions :
    weight_dict[region] = db_ref_regions[db_ref_regions["Acronym"]==region]['area'].values[0]/europe_area

In [7]:
db_ref_regions

,Continent,Type,Name,Acronym,area,%area,geometry
0,POLAR,Land,Greenland/Iceland,GIC,4.773859e+10,0.93586,"MULTIPOLYGON (((-10 62, -10.4375 62, -10.875 6..."
1,NORTH-AMERICA,Land,N.W.North-America,NWN,7.508144e+10,1.47189,"MULTIPOLYGON (((-105 50, -105.4386 50, -105.87..."
2,NORTH-AMERICA,Land,N.E.North-America,NEN,7.664688e+10,1.50258,"MULTIPOLYGON (((-50 50, -50.44 50, -50.88 50, ..."
3,NORTH-AMERICA,Land,W.North-America,WNA,3.138781e+10,0.61532,"MULTIPOLYGON (((-130 50, -129.5614 50, -129.12..."
4,NORTH-AMERICA,Land,C.North-America,CNA,2.931387e+10,0.57467,"MULTIPOLYGON (((-90 50, -90 49.5614, -90 49.12..."
5,NORTH-AMERICA,Land,E.North-America,ENA,5.686132e+10,1.11471,"MULTIPOLYGON (((-70 25, -70.43478 25, -70.8695..."
6,CENTRAL-AMERICA,Land,N.Central-America,NCA,3.161337e+10,0.61975,"MULTIPOLYGON (((-90 25, -90.37179 24.76923, -9..."
7,CENTRAL-AMERICA,Land,S.Central-America,SCA,3.851208e+10,0.75499,"MULTIPOLYGON (((-75 12, -75.28 11.67333, -75.5..."
8,CENTRAL-AMERICA,Land-Ocean,Caribbean,CAR,3.032671e+10,0.59452,"MULTIPOLYGON (((-75 12, -75.32609 12.28261, -7..."
9,SOUTH-AMERICA,Land,N.W.South-America,NWS,3.121109e+10,0.61186,"MULTIPOLYGON (((-75 12, -74.57143 12, -74.1428..."
10,SOUTH-AMERICA,Land,N.South-America,NSA,5.252933e+10,1.02978,"MULTIPOLYGON (((-72 12, -71.5641 12, -71.12821..."
11,SOUTH-AMERICA,Land,N.E.South-America,NES,3.861431e+10,0.75699,"MULTIPOLYGON (((-34 -20, -34.43243 -20, -34.86..."
12,SOUTH-AMERICA,Land,South-American-Monsoon,SAM,2.986145e+10,0.58540,"MULTIPOLYGON (((-66.4 -20, -66.71111 -19.72222..."
13,SOUTH-AMERICA,Land,S.W.South-America,SWS,2.615453e+10,0.51273,"MULTIPOLYGON (((-72 -15, -71.68889 -15.27778, ..."
14,SOUTH-AMERICA,Land,S.E.South-America,SES,5.022881e+10,0.98468,"MULTIPOLYGON (((-34 -20, -34.32353 -20.29412, ..."
15,SOUTH-AMERICA,Land,S.South-America,SSA,2.530203e+10,0.49602,"MULTIPOLYGON (((-79 -56, -79 -55.57143, -79 -5..."
16,EUROPE,Land,N.Europe,NEU,5.003935e+10,0.98097,"MULTIPOLYGON (((-10 48, -10 48.43929, -10 48.8..."
17,EUROPE,Land,West&Central-Europe,WCE,3.792353e+10,0.74345,"MULTIPOLYGON (((-10 45, -10 45.42857, -10 45.8..."
18,EUROPE,Land,E.Europe,EEU,2.834520e+10,0.55568,"MULTIPOLYGON (((40 45, 40 45.43478, 40 45.8695..."
19,EUROPE-AFRICA,Land-Ocean,Mediterranean,MED,7.339288e+10,1.43879,"MULTIPOLYGON (((-10 30, -10 30.42857, -10 30.8..."
20,AFRICA,Land,Sahara,SAH,1.002830e+10,1.96594,"MULTIPOLYGON (((-20 14.7, -20 15.13714, -20 15..."
21,AFRICA,Land,Western-Africa,WAF,4.327841e+10,0.84843,"MULTIPOLYGON (((-20 7.6, -20 8.01765, -20 8.43..."
22,AFRICA,Land,Central-Africa,CAF,5.105328e+10,1.00085,"MULTIPOLYGON (((8 -10, 8 -9.56522, 8 -9.13043,..."
23,AFRICA,Land,N.Eastern-Africa,NEAF,3.571635e+10,0.70018,"MULTIPOLYGON (((27 2.3, 27 2.72759, 27 3.15517..."
24,AFRICA,Land,S.Eastern-Africa,SEAF,2.940354e+10,0.57643,"MULTIPOLYGON (((27 -10, 27 -9.56071, 27 -9.121..."
25,AFRICA,Land,W.Southern-Africa,WSAF,4.975870e+10,0.97547,"MULTIPOLYGON (((8 -36, 8 -35.56667, 8 -35.1333..."
26,AFRICA,Land,E.Southern-Africa,ESAF,4.096100e+10,0.80300,"MULTIPOLYGON (((25 -10, 25.43878 -10, 25.87755..."
27,AFRICA,Land,Madagascar,MDG,2.290109e+10,0.44895,"MULTIPOLYGON (((36.2 -27, 36.42391 -26.63043, ..."
28,ASIA,Land,Russian-Arctic,RAR,7.398376e+10,1.45037,"MULTIPOLYGON (((-180 73.8, -179.57143 73.75714..."
29,ASIA,Land,W.Siberia,WSB,4.251781e+10,0.83352,"MULTIPOLYGON (((60 45, 60 45.43478, 60 45.8695..."
30,ASIA,Land,E.Siberia,ESB,5.669040e+10,1.11136,"MULTIPOLYGON (((90 45, 90 45.43478, 90 45.8695..."
31,ASIA,Land,Russian-Far-East,RFE,5.172919e+10,1.01410,"MULTIPOLYGON (((130 45, 130 45.43478, 130 45.8..."
32,ASIA,Land,W.C.Asia,WCA,5.577292e+10,1.09337,"MULTIPOLYGON (((40 30, 40 30.42857, 40 30.8571..."
33,ASIA,Land,E.C.Asia,ECA,2.794029e+10,0.54774,"MULTIPOLYGON (((75 37, 75 37.42105, 75 37.8421..."
34,ASIA,Land,Tibetan-Plateau,TIB,2.344090e+10,0.45953,"MULTIPOLYGON (((75 30, 75 30.4375, 75 30.875, ..."
35,ASIA,Land,E.Asia,EAS,9.464152e+10,1.85535,"MULTIPOLYGON (((100 19.5, 100 19.9375, 100 20...."
36,ASIA,Land,Arabian-Peninsula,ARP,3.401287e+10,0.66679,"MULTIPOLYGON (((33 30, 33.42941 30, 33.85882 3..."
37,ASIA,Land,S.Asia,SAS,5.266011e+10,1.03235,"MULTIPOLYGON (((60 23.5, 60 23.93333, 60 24.36..."
38,ASIA,Land-Ocean,S.E.Asia,SEA,1.607439e+10,3.15121,"MULTIPOLYGON (((93 -10, 93 -9.56618, 93 -9.132..."
39,OCEANIA,Land,N.Australia,NAU,5.348504e+10,1.04852,"MULTIPOLYGON (((110 -20, 110 -19.56522, 110 -1..."
40,OCEANIA,Land,C.Australia,CAU,4.049278e+10,0.79382,"MULTIPOLYGON (((110 -30, 110 -29.56522, 110 -2..."
41,OCEANIA,Land,E.Australia,EAU,1.597793e+10,0.31323,"MULTIPOLYGON (((145.5 -32.9, 145.5 -32.47, 145..."
42,OCEANIA,Land,S.Australia,SAU,5.126151e+10,1.00493,"MULTIPOLYGON (((110 -36, 110 -35.57143, 110 -3..."
43,OCEANIA,Land,New-Zealand,NZ,4.716391e+10,0.92460,"MULTIPOLYGON (((155 -50, 155 -49.56522, 155 -4..."
44,POLAR,Land,E.Antarctica,EAN,1.544580e+10,3.02799,"MULTIPOLYGON (((-180 -90, -180 -89.5625, -180 ..."
45,POLAR,Land,W.Antarctica,WAN,5.332340e+10,1.04535,"MULTIPOLYGON (((-180 -83, -180 -82.56667, -180..."
46,ARCTIC,Ocean,Arctic-Ocean,ARO,6.345420e+10,1.24395,"MULTIPOLYGON (((-180 90, -179.56044 90, -179.1..."
47,PACIFIC,Ocean,N.Pacific-Ocean,NPO,5.161298e+10,10.11818,"MULTIPOLYGON (((132 7.6, 132 8.035, 132 8.47, ..."
48,PACIFIC,Ocean,Equatorial.Pacific-Ocean,EPO,2.881388e+10,5.64866,"MULTIPOLYGON (((-180 -10, -180 -9.56, -180 -9...."
49,PACIFIC,Ocean,S.Pacific-Ocean,SPO,5.326147e+10,10.44135,"MULTIPOLYGON (((-180 -56, -180 -55.5619, -180 ..."
50,ATLANTIC,Ocean,N.Atlantic-Ocean,NAO,2.449906e+10,4.80278,"MULTIPOLYGON (((-50 7.6, -50.32927 7.88537, -5..."
51,ATLANTIC,Ocean,Equatorial.Atlantic-Ocean,EAO,9.250622e+10,1.81349,"MULTIPOLYGON (((-34 -10, -34 -9.56522, -34 -9...."
52,ATLANTIC,Ocean,S.Atlantic-Ocean,SAO,1.950799e+10,3.82433,"MULTIPOLYGON (((-56 -56, -56 -55.56757, -56 -5..."
53,INDIAN,Ocean,Arabian-Sea,ARS,3.189726e+10,0.62531,"MULTIPOLYGON (((53 7, 53 7.42105, 53 7.84211, ..."
54,INDIAN,Ocean,Bay-of-Bengal,BOB,1.500829e+10,0.29422,"MULTIPOLYGON (((79 7, 79.23529 7.36765, 79.470..."
55,INDIAN,Ocean,Equatorial.Indian-Ocean,EIO,9.505260e+10,1.86341,"MULTIPOLYGON (((46.5 -10, 46.5 -9.56071, 46.5 ..."
56,INDIAN,Ocean,S.Indian-Ocean,SIO,1.851720e+10,3.63010,"MULTIPOLYGON (((36.2 -27, 36.63077 -27, 37.061..."
57,SOUTHERN,Ocean,Southern-Ocean,SOO,5.162344e+10,10.12023,"MULTIPOLYGON (((-180 -56, -179.56028 -56, -179..."

In [8]:
# Compute Global Warming Level and Regional Warming Level of the period 1986-2005
db_avg = pd.DataFrame(index=range(len(csv_filelist)),columns=["model","world_avg","eurocordex_avg"])
for i in range(len(csv_filelist)) :
    with open(csv_filelist[i],'r') as f :
        model = f.readlines()[4][8:-1] # Get model name
    db_avg.loc[i,"model"] = model
    db_temp = pd.read_csv(csv_filelist[i],sep=",",index_col=0,header=15)
    db_temp_ref = db_temp.loc["1850-01":"1899-12",['NEU','WCE','EEU','MED','world']].mean() # Average of the 1850-1899 period
    db_temp = db_temp.loc["1986-01":"2005-12",['NEU','WCE','EEU','MED','world']].mean() # Average of the 1986-2005 period
    db_avg.loc[i,"world_avg"] = db_temp["world"] - db_temp_ref["world"] # Compute Global Warming Level of 1986-2005
    europe_avg = 0
    europe_avg_ref = 0
    for region in eurocordex_regions :
        # Weigh each european region by its area fraction in order to compute the european average temperature (for period 1986-2005 and reference period 1850-1899)
        europe_avg += db_temp[region]*weight_dict[region]
        europe_avg_ref += db_temp_ref[region]*weight_dict[region]

    db_avg.loc[i,"eurocordex_avg"] = europe_avg - europe_avg_ref # Compute Regional Warming Level of the period 1986-2005

In [9]:
# Show dataframe
db_avg

                        model world_avg eurocordex_avg
0         NorESM2-LM_r1i1p1f1  0.301291       0.241505
1      EC-Earth3-Veg_r1i1p1f1   1.08569       2.167852
2         ACCESS-CM2_r1i1p1f1  0.392181       0.129123
3   EC-Earth3-Veg-LR_r1i1p1f1   0.70588       1.404576
4          FGOALS-g3_r1i1p1f1  0.710552        0.66292
5    HadGEM3-GC31-LL_r1i1p1f3  0.346038       0.173803
6              CESM2_r4i1p1f1    0.6629        0.75702
7      ACCESS-ESM1-5_r1i1p1f1  0.459394       0.546566
8          EC-Earth3_r1i1p1f1  0.446919       0.023128
9            TaiESM1_r1i1p1f1  0.157973      -0.144117
10     MPI-ESM1-2-HR_r1i1p1f1  0.611146        0.71931
11         KIOST-ESM_r1i1p1f1  0.885046       1.038685
12     AWI-CM-1-1-MR_r1i1p1f1  0.809539       0.960394
13            MIROC6_r1i1p1f1  0.397358       0.165895
14     CNRM-CM6-1-HR_r1i1p1f2  0.817894        0.97412
15         INM-CM4-8_r1i1p1f1  0.657139       0.907665
16      IPSL-CM6A-LR_r1i1p1f1  0.870373        1.01789
17     MPI-ESM1-2-LR_r1i1p1f1  0.711671       0.808371
18       CNRM-ESM2-1_r1i1p1f2  0.473728       0.701918
19       BCC-CSM2-MR_r1i1p1f1  0.446002       0.645053
20       CESM2-WACCM_r1i1p1f1  0.653131       0.580948
21          GFDL-CM4_r1i1p1f1  0.448495       0.392931
22        CNRM-CM6-1_r1i1p1f2  0.671514       0.944654
23             NESM3_r1i1p1f1  0.508425       0.808601
24          IITM-ESM_r1i1p1f1  0.771801       0.851966
25           CanESM5_r1i1p1f1  0.905816       1.007318
26        MRI-ESM2-0_r1i1p1f1  0.479064       0.403719
27         GFDL-ESM4_r1i1p1f1  0.419912      -0.016183
28       CAMS-CSM1-0_r2i1p1f1  0.479307        0.74053
29         INM-CM5-0_r1i1p1f1  0.592607       0.692147
30      CMCC-CM2-SR5_r1i1p1f1  0.798388       1.274543
31        KACE-1-0-G_r2i1p1f1  0.993178       1.461349
32        NorESM2-MM_r1i1p1f1  0.326659       0.511645
33        MIROC-ES2L_r1i1p1f2  0.422003        0.20464
34       UKESM1-0-LL_r1i1p1f2  0.326503       0.085509

In [8]:
print("mean global warming: ", db_avg["world_avg"].mean())
print("median global warming: ",db_avg["world_avg"].quantile(0.5))

mean global warming:  0.5927290476190479
median global warming:  0.592606666666665

In [ ]:
print("mean regional warming: ", db_avg["eurocordex_avg"].mean())
print("median regional warming: ",db_avg["eurocordex_avg"].quantile(0.5))

mean regional warming:  0.701918381186525
median regional warming:  0.701918381186525

In [10]:
# Litterature shows the GWL of 1986-2005 is 0.61°C so we use it to correct the computed Regional Warming Level
expected_global_warming = 0.61
european_warming = db_avg["eurocordex_avg"].quantile(0.5)*expected_global_warming/db_avg["world_avg"].quantile(0.5)
print(f"European warming 1986-2005: {european_warming}°C")

European warming 1986-2005: 0.722520073782129°C